services:
  db: 
    env_file: .env
    image: postgres:17.2
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $DB_USER -d $DB_NAME
      interval: 5s
      timeout: 2s
      retries: 5

  backend:
    env_file: .env
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    ports: 
      - 8080:8080 
    depends_on:
      - db
    volumes:
      - ./src:/app
    command: ["go", "run", "main.go", "serve"]

volumes:
  db-volume:
